spring:
  datasource:
    url: jdbc:h2:file:./src/main/resources/db/taskmgnt
    username: sa
    password:
  h2:
    console:
      enable: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
